name: Deploy Node.js API to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH known hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

    - name: Copy files via SSH
      run: |
        rsync -avz --delete . root@134.209.121.246:/var/www/backend

    - name: Restart PM2
      run: ssh -o StrictHostKeyChecking=no root@134.209.121.246 'pm2 restart api'
        rsync -avz --exclude='node_modules' --exclude='.env' --delete . root@134.209.121.246:/var/www/backend

    - name: npm install and Restart PM2 
      run: ssh -o StrictHostKeyChecking=no root@134.209.121.246 'npm install && pm2 restart backend'
